### ISSUE TITLE
[Ashita] loading on default.txt doesn't get player_name

### ISSUE THREAD

**Issue by kaincenteno** [zach2good/captain#4]
![image](https://user-images.githubusercontent.com/26943220/169370242-41f68729-07a7-4a70-bd71-d45e0d47c2d3.png)

loading after game has finished loading works well but if added as default auto load can cause it to fail loading

**Comment by zach2good** [comment]
Fixed in https://github.com/zach2good/captain/commit/82751d670c2e52b34fcf4fcde05c89b1a4735ba0
