### ISSUE TITLE
Windower lua runtime startup error: attempt to index local 'self' (a string value)

### ISSUE THREAD

**Issue by morlin123** [zach2good/captain#6]
Line 154: attempt to index local 'self' (a string value)

**Comment by zach2good** [comment]
Have you got any more information about when this was happening? What were
you doing, etc.?

**Comment by morlin123** [comment]
just loading the addon gives this line loop in windowers console

**Comment by zach2good** [comment]
Fixed in: https://github.com/zach2good/captain/pull/7
